language: python
notifications:
  email:
    recipients:
       - bagilis-csoport@googlegroups.com
    on_success: never # default: change
    on_failure: always # default: always
python:
  - "2.7"
cache: pip
script:
  - python -m Stomp.test.run_unittest

