language: python
notifications:
  email:
    recipients:
       - pnat91@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
python:
  - "2.7"
cache: pip
script:
  - python ./test/run_unittest.py

